### ISSUE TITLE
Network Issue on using animdl

### ISSUE THREAD

**Issue by DeePSiDeinside** [justfoolingaround/animdl#203]
I have a propper network connection in my linux distro but whenever im running a query im always getting :

`animdl-http: ERROR] ConnectTimeout('timed out'), this issue originates due to connection issues on your or the server's side. Retry after troubleshooting connection issues on your system.
NoneType: None`
Can you help me out?

**Comment by uzuto** [comment]
It's happening with me as well, I checked and found out that my ISP (Jio) blocked raw.githubusercontent.com which I think is necessary for animdl.

**Comment by yash-10x** [comment]
is there any solution for this problem

**Comment by uzuto** [comment]
> is there any solution for this problem

Only using VPN works.

**Comment by justfoolingaround** [comment]
Use `animdl -x ...` and see if it helps. This will disable update checking.

**Comment by uzuto** [comment]
@justfoolingaround 
Searching is now working fine but the video doesn't play
`TypeError: bufsize must be an integer`

My config.yml
```default_provider: yugen 
default_player: mpv
players:
    mpv:
        executable: mpv
        opts: [--fs]
site_urls:
    9anime: https://www.9anime.gs/
fzf:
    executable: fzf
    opts: [--border=sharp, --height=15, --color=dark]
    state: true
````
here is a log [file](https://pastebin.com/i7nn673a)

a screenrec as well

https://user-images.githubusercontent.com/90568133/212538316-11776fc3-e467-4a81-aa6d-d863d28eb120.mp4

**Comment by justfoolingaround** [comment]
Fixed as of 1.7.2.

**Comment by uzuto** [comment]
> Fixed as of 1.7.2.

Thanks Its working now but I still cant play links from marin(tenshi) provider
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

[log](https://pastebin.com/f8PGqsZq) file
